### ISSUE TITLE
Exhaustive equal-length bin algorithm

### ISSUE THREAD

**Issue by willgearty** [palaeoverse/palaeoverse#18]
It would be nice to have a way to ensure that we have the MOST equal-length bins possible. This could include some sort of algorithm that checks a bunch of different sets of bins and then compares their sds. I'm not sure on the return on investment here, both in terms of developer time and computation time within the function, but I think it might be useful for more statistically-inclined users.

**Comment by LewisAJones** [comment]
Agreed. In reality, the current implementation is probably already giving the user the most equal bins for the specified bin size. I think with an exhaustive method, we could have occasions were more equal time bins are drawn, however the mean bin size will likely be further from the specified bin size. The current implementation is grouping based on a cumulative sum, so it is generally giving you the best grouping for the target bin size. This is just something to be aware of. Maybe in an updated approach, the user wouldn't specify a bin size, and a list of different groupings could be returned with the mean/standard deviation of each. The user would then be able to choose what standard deviation they are happy with for given bin sizes. I would like to hear feedback from the community first though! I think there are different ways to think about these things depending on what you prioritise.

**Comment by KEichenseer** [comment]
I've updated the binning in the `time_bins` function by replacing the previous method with a dynamic programming approach which generates a cost matrix for potential partitionings (cost being (target_bin_size - actual_bin_size)^2) and selects the lowest-cost partitionings. 

This removes the edge effects sometimes present in the previous approach and generally brings average bin sizes closer to the user-specified `size`. Sometimes this better approximation of desired average bin length comes at the cost of higher sd, but I think that's OK - the user can specify different bin sizes if the current size forces relatively uneven spacings. 

I also added a `n_bins` option where the user can specify a desired number of bins instead of bin `size`.

Implemented in PR #131
